persistence:
  data:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi

service:
  main:
    enabled: true
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: 'true'
    ports:
      http:
        port: 8443
        protocol: HTTPS
      controller:
        enabled: true
        port: 8080
        protocol: TCP
      portal-http:
        enabled: false
        port: 8880
        protocol: HTTP
      portal-https:
        enabled: false
        port: 8843
        protocol: HTTPS
      speedtest:
        enabled: true
        port: 6789
        protocol: TCP
      stun:
        enabled: false
      syslog:
        enabled: false
      discovery:
        enabled: false
  udp:
    enabled: true
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: 'true'
    ports:
      stun:
        enabled: true
        port: 3478
        protocol: UDP
      syslog:
        enabled: false
        port: 5514
        protocol: UDP
      discovery:
        enabled: true
        port: 10001
        protocol: UDP
