ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: default-traefik-forward-auth@kubernetescrd
    hosts:
      - host: whoami.tamika.fi
        paths:
          - path: /
            pathType: Prefix
